server:
   port: 8888
   servlet.context-path: autonomy
   
#datasource
spring:
   mvc:
      hiddenmethod:
         filter:
            enabled: true

   datasource:
      # Oracle settings
      
      #Uncomment if we want to connect to oracle by using the JNDI
      #jndi-name: jdbc/autonomy
      url: jdbc:oracle:thin:@devscan1.coface.dns:1521/pdbgridpadv
      username: autonomy
      password: autonomy
      driver-class-name: oracle.jdbc.driver.OracleDriver
      
      # HikariCP settings
      hikari: 
         minimumIdle: 5
         maximumPoolSize: 20
         idleTimeout: 30000
         maxLifetime: 2000000
         connectionTimeout: 30000
      

   jpa:
      #disable schema generation from Hibernate
      show-sql: true
      hibernate.ddl-auto: none      
      #DB dialect - override default one      
      database-platform: org.hibernate.dialect.Oracle10gDialect                             
     
      
      
